#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as follows:
#
#           ksh Gradle
#
#       Or, if you have bash, but not ksh, you can do:
#
#           bash Gradle
#
#   (2) This script attempts to find the Gradle home directory. It uses the
#       GRADLE_HOME environment variable if set. If not set, it searches the
#       current directory and parent directories.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -n is undefined. But in bash and zsh it sets the soft limit.
        # In ksh, ulimit -n -m -c sets the soft limit for the corresponding resource.
        # In POSIX sh, the soft limit for file descriptors can be set with ulimit -n.
        # In bash, it's preferable to do `ulimit -n unlimited` if we support unlimited, because
        # the POSIX version, `ulimit -n 'max'`, sets the hard limit, which is not what we want.
        # We also try to never set the hard limit higher than the hard limit, since that results in
        # an -1 error (invalid argument) on macOS.
        max=
        ulimit_n_cmd="ulimit -n"
        if "$ulimit_n_cmd" 'max' 2>/dev/null; then
            if [ "$(ulimit -n)" = "max" ]; then
                max='max'
            fi
        elif "$ulimit_n_cmd" 'unlimited' 2>/dev/null; then
            if [ "$(ulimit -n)" = "unlimited" ]; then
                max='unlimited'
            fi
        fi
        if [ -n "$max" ]; then
            ulimit_n_cmd="$ulimit_n_cmd $max"
            if ! "$ulimit_n_cmd"; then
                warn "Could not set maximum file descriptor limit to '$max'"
            fi
        fi
        ;;
      * )
        if ! ulimit -n "$MAX_FD"; then
            warn "Could not set maximum file descriptor limit to $MAX_FD"
        fi
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module module-path given)
#   * ... module arguments
#   * some JVM arguments (JAVA_OPTS, GRADLE_OPTS, etc.) and then the ones from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module module-path given)
#   * ... module arguments

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - sh-compatible shells treat it as a switch but
    # the leading double-dash means "everything else", so we escape it.
    set -- "$(cygpath --windows -- "$1")" "${@:2}"
fi

# Collect all arguments for the java command;
#   * $JAVA_OPTS, $GRADLE_OPTS, and their environment counterparts
#   * the arguments to this script (originally in "$@")
#   * the main class name (org.gradle.wrapper.GradleWrapperMain)
#   * -classpath
#   * -D...appname settings
#   * --module-path (if set)
#   * ... module arguments

JAVA_OPTS=$( (grep -v '^#' "$APP_HOME/gradle.properties" || true; echo "$DEFAULT_JVM_OPTS") | tr '\n' ' ' )
GRADLE_OPTS="$JAVA_OPTS $GRADLE_OPTS"
JAVA_OPTS=""

if [ "$1" = "--module-path" ]; then
    shift
    eval "MODULE_PATH=\"$1\""
    shift
    JAVA_OPTS="$JAVA_OPTS --module-path $MODULE_PATH"
fi

if [ -n "$JAVA_OPTS" ] ; then
    # Split JAVA_OPTS over # as a delimeter, then append each to the java command line arguments.
    IFS="#" read -r -a java_opts_array <<< "${JAVA_OPTS// /#}"
    for java_opt in "${java_opts_array[@]}"; do
        java_args+=("$java_opt")
    done
fi

if [ -n "$GRADLE_OPTS" ] ; then
    IFS="#" read -r -a gradle_opts_array <<< "${GRADLE_OPTS// /#}"
    for gradle_opt in "${gradle_opts_array[@]}"; do
        java_args+=("$gradle_opt")
    done
fi

# Check if a --debug option was given
if printf '%s\n' "$@" | grep -q -e '--debug'; then
    JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*
"
    # Debug logging for wrapper script.
    echo "DEBUG: JAVA_OPTS=$JAVA_OPTS" >&2
    echo "DEBUG: GRADLE_OPTS=$GRADLE_OPTS" >&2
fi

# Collect the arguments to the java command
# For Hyphens: well-named options have hyphens, but the class name might have spaces?
# For performance, split on known tokens, then re-evaluate each word as if it were a shell
# token but without performing expansion, because the original (non-weird) shell did not
# expand any of the following characters: ~ $ ( ) ; < > \ | (except the ones we add).
# (Note that we need not worry about IFS because the callers are not expecting any
# word splitting, and there are no word globs or expansions because we did not call
# any of those functions. In particular, the callers are not expecting any word
# splitting to happen, so we do not do it.)

# The first argument might be `--` because the user gave that to GNU env. Keep it as
# part of the arguments to the java command.
set -- "${@:1}" "org.gradle.wrapper.GradleWrapperMain" "${java_args[@]}" "$@"

eval "set -- $(
    printf '%s\n' "$1" |
    sed -e "s/'/'\\\\''/g;" \
        -e '1s/^/'/"'" -e '1s/$/"'/' \
        -e '$!d'
)" "$@" || exit

# We dont support module path on windows because we can't create the path mapping anyway.
# shellcheck disable=SC2086
exec "$JAVACMD" "$@"
